version: '3.8'

services:
  flaskapp:
    image: felipealfah/ninjaapi:1.2
    ports:
      - "80:80"
    depends_on:
      - chrome
    networks:
      - app-network

  selenium-hub:
    image: selenium/hub:4.20
    ports:
      - "4444:4444"
    networks:
      - app-network

  chrome:
    image: selenium/node-chrome:4.20
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    networks:
      - app-network

  # Descomente para usar Firefox
  firefox:
     image: selenium/node-firefox:4.20
     shm_size: 2gb
     depends_on:
       - selenium-hub
     environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
     networks:
       - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

